# audio-feedback-visual
= Audio Feedback Visual

El programa de feedback visual de audio, o [acepto sugerencias de nombres con mas onda],  sirve para darle un paciente una noción del volumen de los ruidos que produce, ya sean percusivos o hablados.

El programa tambien produce archivos de log, en formato CSV (datos separados por coma), que pueden utilizarse para medir el progreso de un paciente a lo largo del tiempo.

Existen tambien una serie de parametros que se pueden ajustar según las condiciones sonoras del lugar, para filtrar ruidos indeseados.


== Instalación

Lo primero a tener en cuenta es el sistema operativo usado, ya que existen dos versiones diferentes del programa. Una de 32 bits y otra de 64 bits. Cada una corre unicamente en computadoras con sistemas operativos compatibles.

[NOTE]
La versión de windows es indiferente (sea vista, windows 7, windows 8, etc), lo que importa es si es un sistema operativo de 32 bits o 64 bits ( a veces también llamados 32x o 64x).

Una vez sabido ese dato, hacer lo siguiente:

. Descargar el archivo `audio-feedback.7z` ( si es para 64 bits ) o `audio-feedback-32.7z` (si es para 32 bits)
. Descomprimirlo en la carpeta deseada
. Abrir la carpeta `adudio-feedback`  (o `audio-feedback-32`) y abrir el archivo `audio-feedback.exe` (o `audio-feedback-32.exe`)

Listo!  El programa no requiere instalacion.

[WARNING]
====
En caso de que al intentar abrir el programa surja un mensaje de error alertando sobre la falta de paquetes o librerias de Visual C++ o similar, es porque a la computadora le faltan algunos complementos instalados. Lo que hay que hacer es descargar estas librerias desde la pagina de Microsoft. Es rapido, facil y gratuito.

Hay que instalar *Paquetes redistribuibles de Visual C++ para Visual Studio 2013*

Desde el siguiente link: https://www.microsoft.com/es-ar/download/details.aspx?id=40784
====


== Configuración

=== Encendido y Apagado

Para encender o apagar el audio, dar click en el botón con el ícono del micrófono.

[TIP]
Se puede también alternar entre prendido y apagado con la tecla ESPACIO, o se puede también apagar con la tecla ESCAPE.

=== Modos

El programa tiene dos modos diferentes, uno pensado para canto y otro para percusión. La diferencia está en que el modo percusión busca picos en volumen y registra sólo el pico, mientras que el modo canto promedia el volumen entre las últimas fracciones de segundo para alisar los silencios entre sílabas y registra el volumen a intervalos regulares siempre que haya sonido.

Para elegir un modo u otro, elegir entre ambas opciones en el menú de la derecha.

=== Objetivo

Existen 3 opciones predeterminadas a elegir,

también se peude elegir una opción intermedia dando click en la barra

el color de la barra  depende de lo lejos que esté del objetivo, sea por arriba o por debajo
=== Ajuste Fino


Para reducir rudio de ambiente se puede

filtro graves 
filtro agudo

filtro ruido:  si el volumen del audio en un determinado momento es menor que x, se considera que hay silencio y no se registra nada


== Registros

Segun el modo, varia el intervalo de los registros, pero los valores son los mismos

el valor diferencia es relativo al objetivo seleccionado
